---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  
  - name: Pause 2 minutes
    pause:
      minutes: 2

  - name: Create Nginx Ingress
    shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml

